/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Add docblocks to autocompleted callback functions
 */
export type EnableDocblocks = boolean;
/**
 * Add type declarations (also known as type hints) to autocompleted callback functions
 */
export type EnableTypeDeclarations = boolean;
/**
 * PHP 7.2 or higher is required to support the full set of type declaration features. If you need to support an older version of PHP, select it here and only the types available in that version of PHP will be used
 */
export type SupportOlderPHPVersions = "None" | "7.1" | "7.0" | "5.6";
/**
 * Filepath to a JSON representation of hooks generated by [wp-hooks/generator](https://github.com/wp-hooks/generator).
 */
export type Filepath = string;
/**
 * [LiquidJS](https://liquidjs.com/tutorials/intro-to-liquid.html) template for documentation links for this file's hooks.
 */
export type DocumentationLinkTemplate = string;
/**
 * Add recognized hooks using local files.
 */
export type CustomHooks = (
  | Filepath
  | {
      file: Filepath;
      docLinkTemplate?: DocumentationLinkTemplate;
    }
)[];

export interface WordPressHooksIntelliSense {
  "vscode-wordpress-hooks.docBlocks.enable"?: EnableDocblocks;
  "vscode-wordpress-hooks.typeDeclarations.enable"?: EnableTypeDeclarations;
  "vscode-wordpress-hooks.typeDeclarations.olderPhpVersionSupport"?: SupportOlderPHPVersions;
  "vscode-wordpress-hooks.customHooks.hooks"?: CustomHooks;
}
